################ Eureka?? ################
server:
  port: 8762

eureka:
  instance:
    hostname: eureka2 #eureka????????
  client:
    # ??Eureka?????????
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      # 两个EUreka Server 端口为8761 8762
      defaultZone: http://eureka1:8761/eureka