

################ ?????? ################
server:
  port: 8040
  servlet:
    context-path: /register
spring:
  application:
    # ???Eureka????
    name: register

################ Eureka?? ################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka


