


################ ?????? ################
server:
  port: 8050
  servlet:
    context-path: /login
spring:
  application:
    # ???Eureka????
    name: login

################ Eureka?? ################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka


