server:
  port: 4178 # ??????????

spring:
  application:
    name: couponService # ????????

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    prefer-ip-address: true


